<style>
    .autocomplete-suggestions {
        overflow: auto;
        border: 1px solid #CBD3DD;
        background: #FFF;
    }
    .autocomplete-suggestions strong {
        color: #029cca;
        font-weight: normal;
    }
    .autocomplete-suggestion {
        cursor: pointer;
    }
</style>
<script>
    jQuery( document ).ready(function( $ ) {
        var pastValue = '';
        var HTML = '';

        $('body').on('keydown.remoteList', 'input.attrsearch', function() {
            var ac = $(this).autocomplete({
                serviceUrl: '<?php echo Mage::getUrl() . 'admin/df/search/key/' .  Mage::getSingleton('adminhtml/url')->getSecretKey(); ?>/?isAjax=1',
                minChars: 2,
                maxHeight: 400,
                width: 300,
                zIndex: 9999,
                deferRequestBy: 0,
                params: {form_key: '<?php echo Mage::getSingleton('core/session')->getFormKey() ?>'},
                paramName: 'dynamic_filter',
                type: 'POST',
                width: 124,
                onSelect: function(value, data) {
                    var formURL = '<?php echo Mage::getUrl() . 'admin/df/filter/key/' .  Mage::getSingleton('adminhtml/url')->getSecretKey(); ?>/?isAjax=1';
                    $.ajax(
                        {
                            url : formURL,
                            type: "POST",
                            data : 'dynamic_filter=' + value.data + '&form_key=' + '<?php echo Mage::getSingleton('core/session')->getFormKey() ?>&previous_value=' + pastValue,
                            success:function(data, textStatus, jqXHR)
                            {
                                pastValue = '';
                                productGridJsObject.doFilter();
                            }
                        });
                }
            });
        });

        $('body').on('click', '.edit-filter', function(e) {
            var parent = $(this).parent('span');
            var filter = $($($(parent).children('a')[0]).children('span')).text();
            pastValue = $($(parent).children('a')[0]).attr('name');
            HTML = $(parent).html();
            $(parent).html('<input value="' + filter + '" name="dynamic_filter" class="attrsearch" placeholder="Dynamic filter" /><img class="cancel-edit" src="/skin/adminhtml/default/default/images/rule_component_remove.gif" style="text-align: left; display: inline; cursor: pointer; padding-top: 2px;">');
        });

        $('body').on('click', '.cancel-edit', function(e) {
            var parent = $(this).parent('span');
            $(parent).html(HTML);
        });

        $('body').on('click', '.delete-filter', function(e) {
            var parent = $(this).parent('span');
            var filter = $($(parent).children('a')[0]).attr('name');
            var formURL = '<?php echo Mage::getUrl() . 'admin/df/delete/key/' .  Mage::getSingleton('adminhtml/url')->getSecretKey(); ?>/?isAjax=1';
            $.ajax(
                {
                    url :    formURL,
                    type:    "POST",
                    data :   'dynamic_filter=' + filter + '&form_key=' + '<?php echo Mage::getSingleton('core/session')->getFormKey() ?>',
                    success: function(data, textStatus, jqXHR)
                    {
                        productGridJsObject.doFilter()
                    }
                });
        });
    });
</script>