<form action="http://edu.oggettoweb.ru/homework/payment/form.php" method="post" id="form_redirect">
	<?php foreach(Mage::helper('pay')->getRenderParams() as $key => $value):	?>
		<input type='hidden' name='<?php echo $key?>' value='<?php echo $value;?>' />
	<?php endforeach;?>
</form>

<script type="text/javascript">
    function send () {
        var frm = document.getElementById("form_redirect");
        frm.submit();
    }
//    window.onload = send;
</script>
 
