<h1>List Question</h1>
<ul>
    <?php foreach ($this->_entities as $question): ?>
        <li>
            <ul>
                <li>Name: <?php echo $question->getName(); ?></li>
                <li>Email: <?php echo $question->getEmail(); ?></li>
                <li>Question: <?php echo $question->getQuestion(); ?></li>
                <li>Time: <?php echo $question->getTimestamp(); ?></li>
                <li>Answer: <?php echo $question->getAnswer(); ?></li>
            </ul>
        </li>
        <br/>
    <?php endforeach; ?>
</ul>
<?php echo $this->getChildHtml('pager'); ?>
